### ISSUE TITLE
What does the number in the square brackets mean in the model name GenuineIntel-6-55-[56789ABCDEF]?

### ISSUE THREAD

**Issue by sk-buff** [intel/perfmon#125]
Hi, I'm trying to find the events file corresponding to my CPU with the following parameters:

vendor_id          : GenuineIntel
cpu family         : 6
model                : 85
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
stepping            : 7

I found there are two different family-model names in the mapfile.csv for the 6-55 family CPUs, which are GenuineIntel-6-55-[01234] and GenuineIntel-6-55-[56789ABCDEF]. I'm not sure which one I should choose for my CPU because I don't know the meaning of the number in the square brackets. Does it mean the stepping number or something else? Thank you.

**Comment by edwarddavidbaker** [comment]
Thanks for opening an issue. You are correct. The 4210R is a Cascade Lake https://www.intel.com/content/www/us/en/products/sku/197098/intel-xeon-silver-4210r-processor-13-75m-cache-2-40-ghz/specifications.html . Please use https://github.com/intel/perfmon/tree/main/CLX .

----

Below is a snippet from `Table 2-1` in the [Intel® 64 and IA-32 Architectures Software Developer’s Manual Combined Volumes: 1, 2A, 2B, 2C, 2D, 3A, 3B, 3C, 3D, and 4](https://cdrdv2.intel.com/v1/dl/getContent/671200) .
| DisplayFamily_DisplayModel | Processor Families / Processor Number Series |
| --- | --- |
| 06_55H | Intel® Xeon® Scalable Processor Family based on Skylake microarchitecture, 2nd generation Intel® Xeon® Scalable Processor Family based on Cascade Lake product, and 3rd generation Intel® Xeon® Scalable Processor Family based on Cooper Lake product |

Since `0x55` is used for both Intel® Xeon® products based on Skylake (SKX in the folder structure here) and Cascade Lake (CLX) the steppings are included in `mapfile.csv`. As one example difference, compare `Table 20-44` (CPUID signature: 06_55H) and `Table 20-45` (CPUID signature: 06_55H, Steppings **0x5H - 0xFH**) in the above software developer manual.

Another helpful reference to bookmark is https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/include/asm/intel-family.h .

**Comment by edwarddavidbaker** [comment]
Please re-open if you have additional questions.

**Comment by sk-buff** [comment]
Thanks @edwarddavidbaker. The `Table 2-1` locates in Volume 4, while the `Table 20-44` and the `Table 20-45` locate in Volume 3, for the convenience of future reference :)
