### ISSUE TITLE
TMA counts os code ? 

### ISSUE THREAD

**Issue by songmuhan** [intel/perfmon#132]
hi there, I am wandering whether the TMA counts the OS code ? Or it can be configured ?

**Comment by 1perrytaylor** [comment]
There are specific metrics that report kernel counts such as kernel_utilization and kernel_cpi.

**Comment by captain5050** [comment]
If you are using the Linux `perf` command (I forget which version we added this ability but it has been there a little while), you can add modifiers to metrics the same way you can events. So `:k` on an event says you want only kernel cycles (see the event modifiers in the perf-list man page) and for a metric this will be copied onto the events so:
```
$ sudo perf stat --metric-only -M TopdownL1:k -a sleep 1

 Performance counter stats for 'system wide':

    %  tma_retiring:k %  tma_backend_bound:k %  tma_frontend_bound:k %  tma_bad_speculation:k 
                 6.5                    25.6                     40.9                      26.9 

       1.002802834 seconds time elapsed
```
will gather the TopdownL1 metrics only within the kernel. Using `:u` instead of `:k` would give you a breakdown of only user slots, etc.

**Comment by songmuhan** [comment]
Great, thank you :)
